project:
  type: book
  output-dir: docs

book:
  title: "Inferencia e introducción a los modelos estadísticos con R"
  subtitle: "Curso intersemestral de Invierno - Posgrado de Ciencias Políticas y Sociales"
  author: "Ana Escoto"
  date: "01/09/2023"
  site-url: https://aniuxa.github.io/posgrado_modelo3/
  repo-url: https://github.com/aniuxa/posgrado_modelo3/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - instala.qmd
    - P1.qmd
    - P2.qmd
    - P3.qmd
    - P4.qmd
    - anexo.qmd
  
format:
  html:
    theme:
      light: lumen
      dark: darkly
  pdf: 
    documentclass: report

editor: visual

