# Introducción al curso {.unnumbered}

## Objetivo general

Que  el estudiantado sea capaz de realizar inferencia estadística y modelado de una variable dependiente utilizando R aplicado a las bases de datos mexicanas.

## Temas

**1.	 Revisión de elementos estadísticos básicos desde “tidyverse” **

a.	Tablas de múltiples entradas

b.	Repaso de ggplot2


**2.	Pruebas de hipótesis e intervalos de confianza **

a.	De una sola media

b.	De dos medias

c.	Medias apareadas

d.	Proporciones

e.	Diferencia de proporciones

f.	Chi-cuadrado de independencia

g.	Prueba ANOVA de un solo factor

h.	Pruebas no parámetricas

**3.	Factores de expansión y diseño muestral complejo**

a.	De “survey” a “srvyr”

b.	Tabulados

c.	Intervalos de confianza para medias y cuantiles

**4.	Introducción al modelo de regresión lineal**

a.	Simple

b.	Múltiple

c.	Evaluación de supuestos

**5.	Introducción a los modelos lineales generalizados **

a.	Introducción a la regresión logística

b.	Evaluación de supuestos

c.	Efectos marginales

d.	Interacciones y efectos de más de primer orden


## Metodología

La metodología del curso consistirá en lo siguiente:

*1. La exposición de la facilitadora*. Durante la primera parte de la sesión, se expondrán los comandos necesarios para llevar a cabo cada tema. Se dará una introducción sobre la temática y se buscará dar ejemplos concretos para facilitar el aprendizaje. Se espera que el personal exponga sus dudas o comentarios a lo largo de la explicación.

*2. Realización de ejercicios prácticos*. Al final de cada sesión, corresponderá a las personas asistentes del curso realizar individualmente o en parejas un ejercicio relacionado con lo visto en la primera parte de la clase.

*3. Consulta autónoma de material*. Tanto la exposición como los ejercicios serán acompañado de material de consulta realizado ad hoc para el curso y el contenido, de tal manera que el estudiantado pueda volver a los códigos y las explicaciones posteriormente.

## Proyecto en posit.cloud

<https://posit.cloud/content/5191591>

Con este proyecto se trabajará a lo largo del curso

## Versiones anteriores

Esta es la tercera vez que se imparte el curso. Las versiones anteriores están

- <https://aniuxa.github.io/posgrado_modelo/>
- <https://aniuxa.github.io/posgrado_modelo2/>

## Facilitadora

### Ana Ruth Escoto Castillo

Doctora en Estudios de Población. Centro de Estudios Demográficos y Urbanos, El Colegio de México.

**Semblanza**

Profesora de tiempo completo en la Facultad de Ciencias Políticas y Sociales. Investigadora nivel I en elSistema Nacional de Investigadores. Maestra en Población y Desarrollo por la Facultad Latinoamericana de Ciencias Sociales (FLACSO) -- Sede México. Posee experiencia en recolección de información estadística, diseño y control de procesos de recolección y su procesamiento. Ha aplicado diversos métodos y herramientas multivariadas, homologación de información y comparabilidad de fuentes en sus investigaciones, así como usa de diversos softwares estadísticos, y ha impartido clases de estadítica aplicada a nivel de licenciatura y posgrado. Es co-coordinadora del Capítulo de CDMX de la iniciativa RLadies.
